### ISSUE TITLE
Support team drive 

### ISSUE THREAD

**Issue by feralsja** [Yotsubal/YPlayer-Google-Drive-Proxy#1]
this script is very good, it seems like it still doesn't support team drive files

https://drive.google.com/file/d/1P7bu3IWfZj-tna2aWB2c_JKv34c8jNFK/view

I tried with this video ID stored on the team drive does not work

**Comment by deshitunes** [comment]
Not working. it's showing as.....
"Please input a valid ID"
tried several method as:
1. https://drive.google.com/file/d/GOOGLE_DRIVE_ID/view
2. https://drive.google.com/file/d/GOOGLE_DRIVE_ID
would you please check it ?
