### ISSUE TITLE
Not working & showing "Please input a valid ID"

### ISSUE THREAD

**Issue by endhash** [Yotsubal/YPlayer-Google-Drive-Proxy#2]
Not working. it's showing as.....
"Please input a valid ID"
tried several method as:

https://drive.google.com/file/d/GOOGLE_DRIVE_ID/view
https://drive.google.com/file/d/GOOGLE_DRIVE_ID
would you please check it ?

**Comment by Yotsubal** [comment]
Input only the `GOOGLE_DRIVE_ID` not the google drive url

**Comment by intervals85** [comment]
yes, i try the script still showing "Please input a valid ID"
1P7bu3IWfZj-tna2aWB2c_JKv34c8jNFK
